name: CI - Build Check

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX (test only)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 2026/ia-geografia-ufv/slides.tex
          latexmk_use_xelatex: true
